export const resList = [
  {
    type: "restaurant",
    data: [
      {
        id: 1,
        name: "The Gourmet Kitchen",
        cuisine: "Italian",
        rating: 4.7,
        address: "123 Main St, New York, NY",
        contact: "(123) 456-7890",
        is_open: true,
      },
      {
        id: 2,
        name: "Spice Delight",
        cuisine: "Indian",
        rating: 4.5,
        address: "456 Curry Ave, Los Angeles, CA",
        contact: "(987) 654-3210",
        is_open: true,
      },
      {
        id: 3,
        name: "Sushi Express",
        cuisine: "Japanese",
        rating: 4.6,
        address: "789 Ocean Blvd, San Francisco, CA",
        contact: "(111) 222-3333",
        is_open: false,
      },
      {
        id: 4,
        name: "Burger Haven",
        cuisine: "American",
        rating: 4.2,
        address: "321 Fast Food St, Chicago, IL",
        contact: "(555) 666-7777",
        is_open: true,
      },
      {
        id: 5,
        name: "Vegan Bites",
        cuisine: "Vegan",
        rating: 4.8,
        address: "654 Greenway, Austin, TX",
        contact: "(888) 999-0000",
        is_open: true,
      },
      {
        id: 6,
        name: "Taco Fiesta",
        cuisine: "Mexican",
        rating: 4.4,
        address: "111 Fiesta Ln, Miami, FL",
        contact: "(777) 888-9999",
        is_open: false,
      },
      {
        id: 7,
        name: "Dragon Wok",
        cuisine: "Chinese",
        rating: 4.3,
        address: "222 Chinatown, Seattle, WA",
        contact: "(333) 444-5555",
        is_open: true,
      },
      {
        id: 8,
        name: "BBQ Junction",
        cuisine: "Barbecue",
        rating: 4.7,
        address: "777 Smokehouse Rd, Dallas, TX",
        contact: "(999) 000-1111",
        is_open: true,
      },
      {
        id: 9,
        name: "Mediterranean Flavors",
        cuisine: "Mediterranean",
        rating: 4.6,
        address: "555 Olive St, Phoenix, AZ",
        contact: "(222) 333-4444",
        is_open: true,
      },
      {
        id: 10,
        name: "French Delicacy",
        cuisine: "French",
        rating: 4.9,
        address: "999 Parisian Ave, New Orleans, LA",
        contact: "(666) 777-8888",
        is_open: false,
      },
    ],
  },
];
